Clear string scope for subexpressions within strings
michaelblyons/PowerShell pull request #2
Opened 2022-05-02 01:17 UTC by jwortmann

... and use the common scope conventions for string interpolations. This enables ST's brackets matching within `$(...)` in strings.

![powershell](https://user-images.githubusercontent.com/6579999/166173188-8f1428d7-1ee9-4706-88f2-981042ef2c72.gif)

Also changed the dubious `interpolated.simple.source.powershell` scope for normal parentheses to `meta.group.powershell`, not sure whether the former scope had any special purpose?

2022-05-05 18:31 UTC, jwortmann commented
@michaelblyons Could you please review when you have time?

2022-05-06 00:36 UTC, michaelblyons commented
Sorry. I missed the notification on the original PR.

2022-05-10 18:46 UTC, michaelblyons requested changes
Thanks for these suggestions. Minor changes requested, but overall a nice improvement.

2022-05-10 18:46 UTC, michaelblyons commented on Tests/syntax_test_PowerShell.ps1
> +#^^^^^^^^^^^ meta.string string.quoted.double
Can you put `meta.string` on its own line that runs the whole length?

2022-05-10 18:46 UTC, michaelblyons commented on PowerShell.sublime-syntax
> +        - meta_scope: meta.interpolation.powershell
If we're following Python's conventions, we should also add a `meta_content_scope` with `source.powershell.embedded`, right?

2022-05-10 19:37 UTC, jwortmann commented on PowerShell.sublime-syntax
> +        - meta_scope: meta.interpolation.powershell
Right, it is described in the scope naming guidelines too, but I must have missed it. Done.

2022-05-10 20:39 UTC, michaelblyons approved these changes

2022-05-10 20:46 UTC, merged